InAppBrowser Launcher
fuse-open/fuselibs pull request #1412
Opened 2021-04-06 11:54 UTC by ichan-mb

launch `InAppBrowser` using `SFSafariViewController` on iOS and Chrome `CustomTabs` on Android

# Example:
```
App Background="#000">
	<JavaScript>
		module.exports.launch = function(args) {
		    var inAppBrowser = require("FuseJS/InAppBrowser");
		    inAppBrowser.openUrl("https://fuseopen.com");
		}
	</JavaScript>
	<StackPanel Margin="20">
		<Button Margin="10" Text="Launch InApp Browser">
			<Clicked>
				<LaunchInAppBrowser Url="https://fuseopen.com" />
			</Clicked>
		</Button>
		<Button Margin="10" Text="Launch InApp Browser Via JS">
			<Clicked Handler="{launch}" />
		</Button>
	</StackPanel>
</App>
```
This PR contains:
- [ ] Changelog
- [ ] Documentation
- [ ] Tests

2021-04-06 23:45 UTC, ichan-mb commented
The test is failing on AppVeyor: https://ci.appveyor.com/project/fusetools/fuselibs-public/builds/38573794#L189

some references:
- https://stackoverflow.com/questions/49512629/default-interface-methods-are-only-supported-starting-with-android-n
- https://developer.android.com/studio/write/java8-support.html#supported_features

but testing on my local computer it works fine without modification on `build.gradle` as per reference suggests 🤔

2021-10-06 14:16 UTC, mortend commented
I will try looking into the AppVeyor one day soon, and maybe we'll get this in for 2.0.

2021-11-11 18:02 UTC, ckarmy commented
Any news about these?

2021-11-11 18:48 UTC, mvondoyannick commented
> Any news about this?

Waiting and waiting again 😃

2021-11-12 15:57 UTC, mortend commented
@ichan-mb We got this error message on AppVeyor now when I tried.

```
AGPBI: {"kind":"error","text":"Static interface methods are only supported starting with Android N (--min-api 24): androidx.browser.trusted.TrustedWebActivityDisplayMode androidx.browser.trusted.TrustedWebActivityDisplayMode.fromBundle(android.os.Bundle)","sources":[{}],"tool":"D8"}
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'browser.aar (androidx.browser:browser:1.3.0)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-is-debuggable=true, dexing-min-sdk=16}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\appveyor\.gradle\caches\transforms-2\files-2.1\6561b190abd9d36b94db9426221c2199\browser-1.3.0\jars\classes.jar.
         > Error while dexing.
```

https://ci.appveyor.com/project/fusetools/fuselibs-public/builds/41511066#L203

It sounds like we need to bump min SDK from 16 to 24 to make this work.

2021-11-12 16:10 UTC, Anagrr commented
[Require("Gradle.Dependency.Implementation", "androidx.browser:browser:1.3.0")]

this line cause the error during the build

2021-11-12 16:14 UTC, Anagrr commented
https://stackoverflow.com/a/59184225 look what I found

2021-11-12 17:43 UTC, mortend commented
@Anagrr Nice! I have tried different versions of `androidx.browser:browser`:

* `1.0.0`: works
* `1.1.0`: build error
* `1.2.0`: build error

2021-11-12 18:01 UTC, mortend requested changes

2021-11-12 18:01 UTC, mortend commented on Source/Fuse.Launcher.InAppBrowser/Trigger.uno
> +			<StackPanel Margin="20">
Please use `xml` code-block, or similar to https://github.com/fuse-open/fuselibs/commit/e885f5feee198a71a7f75a015b713e1c8d53af43#diff-e65a11c5d8ba79d36b1a9895f5c70b2dc8959e818f3e951a20da014e593e588dR145

2021-11-12 18:01 UTC, mortend commented on Source/Fuse.Launcher.InAppBrowser/InAppBrowserLauncher.uno
> +	[Require("Gradle.Dependency.Implementation", "androidx.browser:browser:1.3.0")]
Change to `androidx.browser:browser:1.0.0` to make AppVeyor build pass. See https://github.com/fuse-open/fuselibs/pull/1412#issuecomment-967233892.

2021-11-13 01:40 UTC, ichan-mb commented
I have made changes, now AppVeyor run successful

2021-11-13 06:24 UTC, mortend approved these changes
Nice!

2021-11-13 06:24 UTC, merged